name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: |
        apt update
        apt install -yq libssl-dev libsrt-openssl-dev libopus-dev libvpx-dev libsrtp2-dev libfdk-aac-dev nasm ffmpeg libjemalloc-dev libpcre2-dev libopenh264-dev
          
    - name: Build Release
      run: |
        cd src
        make release -j$(nproc)
      
    - name: Release Bianry
      uses: softprops/action-gh-release@v1
      with:
        files: ./bin/RELEASE/OvenMediaEngine
  
